name: aarch64 release builds

on:
  push:
    branches:
      - '*arm64*'
  pull_request:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: windows-11-arm
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "aarch64 posix seh ucrt",
            build_cmd: "--mode=gcc-trunk --buildroot=/c/buildroot --jobs=4 --rev=0 --rt-version=trunk --threads=posix --exceptions=seh --arch=aarch64 --bin-compress --enable-languages=c,c++ --no-bootstrap --no-extras --with-default-msvcrt=ucrt --logviewer-command=cat"
          }
        - {
            name: "aarch64 win32 seh ucrt",
            build_cmd: "--mode=gcc-trunk --buildroot=/c/buildroot --jobs=4 --rev=0 --rt-version=trunk --threads=win32 --exceptions=seh --arch=aarch64 --bin-compress --enable-languages=c,c++ --no-bootstrap --no-extras --with-default-msvcrt=ucrt --logviewer-command=cat"
          }
        - {
            name: "aarch64 mcf seh ucrt",
            build_cmd: "--mode=gcc-trunk --buildroot=/c/buildroot --jobs=4 --rev=0 --rt-version=trunk --threads=mcf --exceptions=seh --arch=aarch64 --bin-compress --enable-languages=c,c++ --no-bootstrap --no-extras --with-default-msvcrt=ucrt --logviewer-command=cat"
          }

    steps:
    - uses: actions/checkout@v3

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          lndir
          git
          subversion
          tar
          zip
          unzip
          p7zip
          make
          patch
          automake-wrapper
          autoconf
          autoconf-archive
          libtool
          flex
          bison
          gettext
          gettext-devel
          wget
          sshpass
          texinfo
          autogen
          dejagnu
          pkgconf

    - name: Install host toolchain
      shell: msys2 {0}
      run: |
        wget -q -P toolchains/ https://github.com/mstorsjo/llvm-mingw/releases/download/20250613/llvm-mingw-20250613-ucrt-aarch64.zip
        unzip -q toolchains/llvm-mingw-20250613-ucrt-aarch64.zip -d toolchains/
        mv toolchains/llvm-mingw-20250613-ucrt-aarch64 toolchains/mingwarm64
        echo "$PWD/toolchains/mingwarm64/aarch64-w64-mingw32/bin" >> $GITHUB_PATH

    - name: Build
      shell: msys2 {0}
      run: ./build ${{ matrix.config.build_cmd }} --provided-toolchain=$(pwd)/toolchains

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: c:/buildroot/archives/*.7z
        name: ${{ matrix.config.name }}
